### ISSUE TITLE
Document requirement for configured certificates api

### ISSUE THREAD

**Issue by drpebcak** [Talend/vault-sidecar-injector#15]
Some k8s distributions - like Rancher's RKE or kubeadm - do not configure a signer. See docs here for info on using the default implementation: https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#a-note-to-cluster-administrators

The requirement for this config (or a signer of some kind) should be documented in the installation steps for this application.

**Comment by asaintsever** [comment]
Thanks for the report. Will update the documentation.

**Comment by asaintsever** [comment]
#17
