### ISSUE TITLE
secrets-template with >1 templates that include range statement causes dest/template mismatch

### ISSUE THREAD

**Issue by smurfralf** [Talend/vault-sidecar-injector#16]
Scenario: I configure secrets-destination and secrets-template with multiple comma delimited values. Because secrets.go splits the annotation strings with "," as the delimiter, a template that includes
 
    {{ range \$k, \$v := .Data }}

will split on the internal comma resulting in error

    Submitted pod must contain same numbers of templates and secrets destinations

**Comment by asaintsever** [comment]
Good catch. Thanks for reporting the issue.

**Comment by asaintsever** [comment]
Fixed via #18
