### ISSUE TITLE
Using secrets in env variables

### ISSUE THREAD

**Issue by kristina-reut** [Talend/vault-sidecar-injector#28]
Hi,

Could you please verify if it is possible to use secrets as env variables in helm chart for app ?

Example:

```
env:    
- name: AWS_SECRET_ACCESS_KEY
    value: "vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY
```

**Comment by asaintsever** [comment]
Hi,
No, such feature is not supported as of today. But it is an interesting use case, I will add that to my todo list. Thanks.

**Comment by kristina-reut** [comment]
Thanks. Is there're any other way to assign a value to env variable from /opt/talend/secret/secrets.properties ?

**Comment by asaintsever** [comment]
One possible solution:
_I assume you are dealing with static secrets here (ie you do not expect values to change and you initialize your env vars once)_

1. Make use of `sidecar.vault.talend.org/secrets-type: "static"` annotation. This way secrets will be fetched early on from an init container and put into `/opt/talend/secret/secrets.properties` file using `KEY=VALUE` pattern (this is the default: https://github.com/Talend/vault-sidecar-injector/blob/master/README.md#default-template). Vault keys should equal your env vars' names.
2. Then, in your deployment k8s manifest, modify the entrypoint of your container to source the secrets properties file (`source /opt/talend/secret/secrets.properties`) before running your program. Env vars should be available and properly valued.

**Comment by kristina-reut** [comment]
Thanks a lot.
