### ISSUE TITLE
Access to the secret.properties

### ISSUE THREAD

**Issue by kristina-reut** [Talend/vault-sidecar-injector#33]
Hello. 
Could you please verify that with using environment variables we haven't the secret file in the pods ? So, we can't access to the secret thought /opt/talend/secrets/secret.properties ?

**Comment by asaintsever** [comment]
Hello,

Internally the feature depends on the secrets file so it is not possible to not "have the secrets file in the pods" but this is totally transparent, you even don't need to explicitly mount a volume. 

Why is it an issue to you? Your process already has access to the secrets via the env vars, why would it be more secure to not have them in files. FYI, the secrets are mounted in a memory volume that only containers in your pod can see and access to.

**Comment by asaintsever** [comment]
After second thought, removing secrets file as I proposed is not a good idea from a resiliency standpoint. If your container restarts, those files will be required to reinject the secrets as env vars in your process.

I will close this ticket as internal implementation depends on those files and there's no security issue keeping them.
