### ISSUE TITLE
error installing the chart: error calling tpl: error during tpl function execution 

### ISSUE THREAD

**Issue by tuananh** [Talend/vault-sidecar-injector#54]
**Describe the issue**
inside the `deploy/helm` folder, i tried `helm template test ./ --debug` and then got this error

```
Error: template: vault-sidecar-injector/charts/vault-sidecar-injector/templates/deployment.yaml:22:28: executing "vault-sidecar-injector/charts/vault-sidecar-injector/templates/deployment.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: vault-sidecar-injector/charts/vault-sidecar-injector/templates/configmap.yaml:9:4: executing "vault-sidecar-injector/charts/vault-sidecar-injector/templates/configmap.yaml" at <tpl (.Files.Get "config/injectionconfig.yaml") .>: error calling tpl: error during tpl function execution for "initContainers:

  - name: tvsi-vault-agent-init
    image: {{ include \"talend-vault-sidecar-injector.injectconfig.vault.image\" .Values }}
    imagePullPolicy: {{ .Values.injectconfig.vault.image.pullPolicy }}

env:
      - name: SKIP_SETCAP
        value: \"true\"
      - name: VAULT_ADDR
        value: {{ required \"Vault server's address must be specified\" .Values.vault.addr | quote }}
      - name: VAULT_LOG_FORMAT
        value: {{ .Values.injectconfig.vault.log.format }}
      # env var set by webhook
      - name: VSI_SECRETS_TEMPLATES_PLACEHOLDER
        value: \"\"
      # env var set by webhook
      - name: VSI_VAULT_ROLE
        value: \"\"
    command:
      - \"sh\"
      - \"-c\"
      - |
        cat <<EOF > vault-agent-config.hcl
        pid_file = \"/home/vault/pidfile\"
        auto_auth {
            method \"kubernetes\" {
              mount_path = \"auth/{{ .Values.vault.authMethods.kubernetes.path }}\"
            config = {
                role = \"${VSI_VAULT_ROLE}\"
              token_path = \"/var/run/secrets/talend/vault-sidecar-injector/serviceaccount/token\"
            }
          }
          sink \"file\" {
              config = {
                path = \"/home/vault/.vault-token\"
            }
          }
        }
        ${VSI_SECRETS_TEMPLATES_PLACEHOLDER}
        EOF

        docker-entrypoint.sh agent -config=vault-agent-config.hcl -exit-after-auth=true {{ include \"talend-vault-sidecar-injector.vault.cert.skip.verify\" .Values }} -log-level={{- .Values.injectconfig.vault.log.level }}
        export VAULT_TOKEN=$(cat /home/vault/.vault-token)
        vault token revoke {{ include \"talend-vault-sidecar-injector.vault.cert.skip.verify\" .Values }} -self
    volumeMounts:
      # Mount path used to share secrets.
      - name: secrets
        mountPath: /opt/talend/secrets
      # The name's value will be overridden by the webhook to point to container's service account volume to use for Vault authentication.
      - name: TVSI_SA_SECR
      - 
 ```

**To Reproduce**

inside the `deploy/helm` folder, i tried `helm template test ./ --debug` and then got this error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

 - Workstation OS: [e.g. Ubuntu 18.04]
 - Kubernetes
    - cluster: [e.g. AKS, EKS, Minikube, Kind, k3s]
    - version of Kubernetes
 - Vault Server
    - version
    - chart version (if Kubernetes install)
    - in-cluster or external instance
 - Vault Sidecar Injector
    - chart version: [e.g. 3.1.1]

**Additional context**

**Content of deployed Kubernetes manifest**

If possible, full content of your manifest with Vault Sidecar Injector annotations and info about your workload such as image path, command, env, volumes & mounts ...

**Log of Vault Server**

Warnings and errors related to the issue

**Logs of Vault Sidecar Injector pod(s)**

Errors reported by Vault Sidecar Injector while trying to inject Vault Agent into your workload

**Logs of your workload**

In particular, logs from the Vault Agent sidecar container injected into your pod

**Comment by asaintsever** [comment]
Hi,

You did not report the interesting part of the error which is, using your command line: `[...]  execution error at (open-vault-agent-injector/templates/deployment.yaml:9:18): Vault server's address must be specified`

It is mandatory to provide the address of the Vault server (see values.yaml file and [configuration](https://github.com/Talend/vault-sidecar-injector/blob/master/doc/Configuration.md) doc).

So, if I do provide this required parameter, it works: `helm template test ./ --set vault.addr=http://vault:8200 --debug`
